### ISSUE TITLE
(Pre)Loading resources

### ISSUE THREAD

**Issue by juansrx** [mayaman26/p5jsCommunitySketches#22]
Good Morning.

After watching my sketch running in my browser many times a doubt came up: In my computer, by example, it takes some time to load things as images, fonts, and objects before running. I don't know how much will it take to the resulting script to load these resources (or, how much machine power will it have available). Will every sketch make a setup/preload call? or everything will be preloaded before running each sketch?, If each sketch makes its own setup/preload calls, should we consider a "time limit"?. Or maybe I should "reduce the weight" of what I'm loading so the "loading..." screen doesn't show up (much).

If you have any other suggestion or stylen guide about this please let me know.

Thanks your help again Maya

**Comment by mayaman** [comment]
Hi Juan,

Last night, I sent out a video test framework that you can put your sketch in to test and see how it works running in the browser with a p5 clip. I would not recommend trying to load too many assets to the point where it takes a very long time for the sketch to start running. Try seeing how the sketch functions in that framework & make adjustments if the "loading" screen appears too long (possibly "reduce the weight" if necessary). 

Cheers!

**Comment by juansrx** [comment]
Hello Maya

After testing my script with the framework I realized I had to put away some details because the video reproduction was PAINFUL (no sync between audio and video, it kept freezing and skipping some frames, and it took a bit to load), this was on my 2.2GHZ Laptop. Testing it in anothe computer (a 2.4 GHZ AMD A8), this improved a lot (still I had to make some changes because the video kept getting out of sync), and the resulting script took ~1 second to preload everything and no freezing or sync problems. But, I had to lower the framerate to 40.

I will try it once more in my home, but maybe you can tell me if I can stick with 40 fps for my script, also I have a "last" question: In my original script I had a relative path to the document root to refer the p5 logo ("../p5-asterisk.png"), in the test framework, the path is "assets/p5-asterisk.png". Which one should be the correct one for my next pull request?

**Comment by mayaman** [comment]
Hi Juan,

I'm sorry you had so much trouble getting the framework set up! I'm glad it improved on another computer, we will fix all of the issues you ran into in our final version of the video. I do not think changing the frame rate to 40 fps will be an issue. It should still run fine with the video and work in between others' sketches who have different frame rates. If it becomes a problem in the future, we will work something out, but you may stick with 40 fps for now. 

In terms of assets path, I would use "assets/p5-asterisk" because that is what the test framework uses. 

Thanks!

**Comment by juansrx** [comment]
Hi Maya

Thanks for answering so quick, all of you have done a lot of work and you
have helped me a lot, don't worry, I don't mind changing back the fps again
or making more changes if needed, just let me know if you need anything
else.

Thanks!

On Tue, Jul 28, 2015 at 8:36 AM, Maya Man notifications@github.com wrote:

> Hi Juan,
> 
> I'm sorry you had so much trouble getting the framework set up! I'm glad
> it improved on another computer, we will fix all of the issues you ran into
> in our final version of the video. I do not think changing the frame rate
> to 40 fps will be an issue. It should still run fine with the video and
> work in between others' sketches who have different frame rates. If it
> becomes a problem in the future, we will work something out, but you may
> stick with 40 fps for now.
> 
> In terms of assets path, I would use "assets/p5-asterisk" because that is
> what the test framework uses.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mayaman26/p5jsCommunitySketches/issues/22#issuecomment-125611600
> .

## 

"porque el fracaso es como el exito...pero al reves"
