### ISSUE TITLE
Issue with the video player

### ISSUE THREAD

**Issue by juansrx** [mayaman26/p5jsCommunitySketches#25]
Hello, sorry to bother you again, I promise it will be the last message for today, I just wanted to report a small "bug"(maybe) when playing the video, I'm using chrome 44.0.2403.89 (64-bit), and I saw the video until it ended, when I pressed "play" again, the video started playing again, but the sketch keep playing and also, it created a new canvas with the sketch below. 

Maybe this is not a big deal I just wanted you to know just in case...

Thank you

**Comment by mayaman** [comment]
Thank you for letting me know! The test framework we sent out is a temporary way of testing your sketch, so we'll be sure to fix this bug when we create the final product.
